name: Patch Dist Paths

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify dist-fixed.zip
        run: ls -lh

      - name: Unzip dist-fixed.zip
        run: unzip -o dist-fixed.zip -d dist

      - name: List dist contents
        run: ls -R dist | head -50

      - name: Patch asset paths
        run: |
          set +e
          for ext in html js css; do
            files=$(find dist -type f -name "*.${ext}")
            if [ -n "$files" ]; then
              echo "Patching $ext files..."
              sed -i 's|/assets/|./assets/|g' $files
            else
              echo "No .$ext files found"
            fi
          done
          set -e

      - name: Show first 20 lines of index.html
        run: head -20 dist/index.html || echo "index.html not found"

      - name: Re-zip patched dist
        run: |
          cd dist
          zip -r ../dist-final.zip .

      - name: Upload patched dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-final
          path: dist-final.zip
